CREATE TABLE Users(
    id SERIAL PRIMARY KEY,
    username VARCHAR (50) NOT NULL UNIQUE,
    email VARCHAR (120) NOT NULL UNIQUE,
    phone VARCHAR (120) NOT NULL UNIQUE,
    tg VARCHAR (120) NOT NULL UNIQUE,
    password VARCHAR (128) NOT NULL
);